import {Button, VerticalBox, HorizontalBox} from "std-widgets.slint";

export component MainWindow inherits Window {
    callback open-file();
    VerticalBox {
        alignment: center;
        HorizontalBox {
        
            Button {
                width: 100px;
                height: 200px;
                text: "Open File";
                clicked => {root.open-file();}
            }
        }
        Text {
            text: "list of files";
        }
    }
}



/*
import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    always-on-top: false;
    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
*/