import {Button, VerticalBox, HorizontalBox} from "std-widgets.slint";

export component MainWindow inherits Window {
    callback open-file();
    VerticalBox {
        alignment: center;
        HorizontalBox {
        
            Button {
                width: 100px;
                height: 200px;
                text: "Open File";
                clicked => {root.open-file();}
            }
        }
        Text {
            text: "list of files";
        }
    }
}