import {Button, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {OpeningPage} from "opening-page.slint";
import {SplitPage} from "split-page.slint";
import {PDFerPalette} from "common.slint";

export component App inherits Window {
    in property <int> active-page : 0;
    background: PDFerPalette.background;
    default-font-family: "Noto Sans";
    min-width: 1200px;
    min-height: 800px;

    preferred-width: 1200px;
    preferred-height: 800px;

    if (active-page == 0) : OpeningPage {}

    if (active-page == 1) : SplitPage {}
}