import { Palette } from "std-widgets.slint";

struct ButtonColors  {
    base: color,
    pressed: color,
    hovered: color,
}

struct ModeColors {
    background: color,
    primary: color,
    secondary: color,
    text-primary: color,
    text-secondary: color,
    destructive: color,
}

export global PDFerPalette  {
    in property <bool> dark-mode: Palette.color-scheme == ColorScheme.dark;

    property <ModeColors> light-mode-colors: {
        background: #FFFFFF,
        primary: #0E133F,
        secondary: #FFBF63,
        text-primary: #000,
        text-secondary: #6284FF,
        destructive: #FF3B30,
    };

    property <ModeColors> dark-mode-colors: {
        background: #122F7B,
        primary: #0E133F,
        secondary: #FFBF63,
        text-primary: #F4F6FF,
        text-secondary: #F4F6FF,
        destructive: #FF3B30,
    };

    out property <color> background: dark-mode ? dark-mode-colors.background : light-mode-colors.background;
    out property <color> primary: dark-mode ? dark-mode-colors.primary : light-mode-colors.primary;
    out property <color> secondary: dark-mode ? dark-mode-colors.secondary : light-mode-colors.secondary;
    out property <color> text-primary: dark-mode ? dark-mode-colors.text-primary : light-mode-colors.text-primary;
    out property <color> text-secondary: dark-mode ? dark-mode-colors.text-secondary : light-mode-colors.text-secondary;
    out property <color> destructive: dark-mode ? dark-mode-colors.destructive : light-mode-colors.destructive;

    out property <length> base-font-size: 16px;
    out property <length> button-width: 130px;
    out property <length> button-height: button-width + 30px;
    out property <length> side-bar-width: 1000px;
    out property <length> side-bar-margin: 500px;
}

export global AppService  {
    // This callback can be implemented in native code using the Slint API
    callback open-file();

}

export global BackendTextEditor {
    pure callback save-file(string, string);
    pure callback read-file(string) -> string;
    pure callback open-text-file() -> string;
}

export global BackendPDF {
    pure callback open-pdf(string);
}

export component Page inherits Rectangle {
    // in property <string> header <=> h.text;
    // in property <bool> has-back-button: false;

    // callback back;
    // // Stop accidentally getting clicks dur to animation only moving page half way offscreen
    // visible: self.opacity > 0;

    // TouchArea { } // protect underneath controls


    // if (root.has-back-button) : Image {
    //     x:0;
    //     source: @image-url("images/back.svg");
    //     image-fit: contain;
    //     y: h.y + (h.height - self.height) / 2;
    //     width: 14px;
    //     height: 24px;

    //     TouchArea {
    //         clicked => { root.back() }

    //         x:0;
    //         width: 150%;
    //     }
    // }

    // h := Text {
    //     font-weight: 900;
    //     y: 46px - self.font-size;
    //     x: root.has-back-button ? 24px + 16px : 0px;
    //     // Allow clicking on the title as well to get back easier when just
    //     // using fingers on a small screen.
    //     if (root.has-back-button) : TouchArea {
    //         clicked => { root.back() }
    //     }
    // }
}