import {Button, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {OpeningPage} from "opening-page.slint";
import {SplitWindow} from "note-page.slint";

export component MainWindow inherits Window {

    op := OpeningPage{}
    sw := SplitWindow{}


    property <bool> state: false;
    states [
        active when !state: {
            sw.opacity: 0;
            op.opacity: 1;
        }
        active when state: {
            op.opacity: 0;
            sw.opacity: 1;
        }
    ]
}