import {Button, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {Page, AppService, PDFerPalette, CustomButton} from "common.slint";

export component OpeningPage inherits Page {
    background: PDFerPalette.background;

    VerticalBox {
        alignment: center;
        HorizontalBox {
        
            CustomButton {
                width: 100px;
                height: 200px;
                text: "Open File";
                clicked => {AppService.open-file();}
            }
        }
        Text {
            text: "list of files";
        }
        
        in property <[{name: string, path: string}]> recent_files: AppService.get-recent-files();

        for file in recent_files: CustomButton {
            text: file.name;
            width: 20%;
            font-size: 20px;
            padding-top: 0px;
            padding-bottom: 0px;
            clicked => {
                AppService.open-recent-file(file.path);
            }
        }
        
    }
}