import {Button, VerticalBox, HorizontalBox} from "std-widgets.slint";
import {Page, AppService, PDFerPalette, CustomButton} from "common.slint";

export component OpeningPage inherits Page {
    background: PDFerPalette.background;

    VerticalBox {
        alignment: center;
        HorizontalBox {
        
            CustomButton {
                width: 100px;
                height: 200px;
                text: "Open File";
                clicked => {AppService.open-file();}
            }
        }
        Text {
            text: "list of files";
        }
    }
}