// Get the render of the pdf
// convert to image

// import { } from "std-widgets.slint";
import { BackendPDF, CustomButton } from "common.slint";
import { Button } from "std-widgets.slint";

export component PDFRender inherits Window {
    in-out property <image> current_image: BackendPDF.display();
    // in-out property <bool> has_previous;
    // in-out property <bool> has_next;

    VerticalLayout {
        // spacing: 10px;
        HorizontalLayout {
            spacing: 10px;
            height: root.height * 0.05;

            CustomButton {
                text: "Previous";
                // enabled: has_previous;
                clicked => {
                    BackendPDF.navigate-previous();
                    current_image = BackendPDF.display();
                }
            }

            CustomButton {
                text: "Next";
                // enabled: has_next;
                clicked => {
                    BackendPDF.navigate-next();
                    current_image = BackendPDF.display();
                }
            }
        }
        Rectangle {
            border-color: yellow;
            border-width: 2px;
            min-width: 20px;
            height: 95%;

            Image {
                source: current_image;
                width: 100%;
                height: 100%;
            }
        }
    }
}
