// Get the render of the pdf
// convert to image

// import { } from "std-widgets.slint";
import { BackendPDF } from "global-callbacks.slint";

export component PDFRender inherits Window {
    property <image> current_image;
    property <bool> has_previous;
    property <bool> has_next;

    callback navigate_previous();
    callback navigate_next();

    VerticalLayout {
        spacing: 10px;

        Rectangle {
            border-color: yellow;
            border-width: 2px;
            min-width: 20px;
            height: 80%;

            Image {
                source: current_image;
                width: 100%;
                height: 100%;
                keep-aspect-ratio: true;
            }
        }

        HorizontalLayout {
            spacing: 10px;

            Button {
                text: "Previous";
                enabled: has_previous;
                clicked => navigate_previous();
            }

            Button {
                text: "Next";
                enabled: has_next;
                clicked => navigate_next();
            }
        }
    }
}
