import { TextEdit, Button } from "std-widgets.slint";
import { TextEditor } from "text-editor.slint";
import {PDFRender} from "pdf-render.slint";
import {Page, PDFerPalette} from "common.slint";


export component SplitPage inherits Page {
    background: PDFerPalette.background;
    border-width: PDFerPalette.page-border-width;
    border-color: black;
    width: 100%;
    height: 100%;
    HorizontalLayout {
        PDFRender { }

        TextEditor { }
    }
}
