import { TextEdit, Button } from "std-widgets.slint";
import {Page, BackendTextEditor} from "common.slint";

export component TextEditor inherits Page {
    in-out property <string> notes-text: "";
    out property <string> txt-file-path: "";

    VerticalLayout {
        TE:=TextEdit {
            font-size: 14px;
            height: 80%;
            width: 50%;
            text: notes-text;
            edited(text) => {
                notes-text = text;
            }
        }

        // Buttons for saving and loading files
        VerticalLayout {
            Button {
                text: "Save";
                clicked => {
                    if(txt-file-path == ""){
                        txt-file-path = BackendTextEditor.open-text-file();
                    }
                    BackendTextEditor.save-file(txt-file-path, notes-text);
                }
            }
            Button {
                text: "Load File";
                clicked => {
                    if(txt-file-path != ""){
                        BackendTextEditor.save-file(txt-file-path, notes-text);
                    }
                    txt-file-path = BackendTextEditor.open-text-file();
                    notes-text = BackendTextEditor.read-file(txt-file-path);
                    TE.text = notes-text;
                }
            }
        }

        TouchArea {
            moved => {
                self.width = self.mouse-x;
            }
        }
    }
}